import{i,S as g}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const h="47115642-a97741713bebc955e7d8d0e17",p="https://pixabay.com/api/",b=async s=>{const t=`${p}?key=${h}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`,r=await fetch(t);if(!r.ok)throw new Error("Failed to fetch images");return(await r.json()).hits},l=s=>{const t=document.querySelector(".gallery"),r=s.map(({webformatURL:a,largeImageURL:e,tags:o,likes:n,views:m,comments:f,downloads:y})=>`
        <div class="gallery__item">
          <a href="${e}">
            <img src="${a}" alt="${o}" loading="lazy" />
          </a>
          <div class="photo-info">
            <p><b>Likes:</b> ${n}</p>
            <p><b>Views:</b> ${m}</p>
            <p><b>Comments:</b> ${f}</p>
            <p><b>Downloads:</b> ${y}</p>
          </div>
        </div>
      `).join("");t.innerHTML=r},u=()=>{const s=document.querySelector(".gallery");s.innerHTML=""},d=()=>{document.querySelector(".loader").classList.remove("hidden")},c=()=>{document.querySelector(".loader").classList.add("hidden")};document.querySelector(".search-form").addEventListener("submit",async s=>{s.preventDefault();const t=document.querySelector('input[name="query"]').value.trim();if(!t){iziToast.error({title:"Error",message:"Please enter a search term."});return}u(),d();try{const r=await searchImages(t);r.length===0?iziToast.error({title:"Error",message:"Sorry, no images found for your search."}):(l(r),new SimpleLightbox(".gallery a").refresh())}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again."})}finally{c()}});document.querySelector(".search-form").addEventListener("submit",async s=>{s.preventDefault();const t=document.querySelector('input[name="query"]').value.trim();if(t===""){i.error({title:"Error",message:"Please enter a search term."}),c();return}u(),d();try{const r=await b(t);r.length===0?i.error({title:"Error",message:"Sorry, no images found for your search."}):(l(r),new g(".gallery a").refresh())}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{c()}});
//# sourceMappingURL=index.js.map
